# Caddy Speedtest
# https://maxchernoff.ca/tools/speedtest
# SPDX-License-Identifier: Apache-2.0+
# SPDX-FileCopyrightText: 2025 Max Chernoff
when:
  - event: [push, pull_request]
    branch: master

steps:
  - name: Build
    image: docker.io/library/golang:1.25-alpine
    pull: true
    commands:
      - apk add make bash
      - make test

  - name: Email on failure
    image: docker.io/deblan/woodpecker-email:latest
    when:
        status:
          - failure
    settings:
        level: failure
        dsn:
            from_secret: EMAIL_DSN
        from:
            address: "woodpecker@noreply.maxchernoff.ca"
        recipients:
          - "server-status@maxchernoff.ca"
        recipients_only: true
        content:
            subject: >
                [{{ pipeline.status }}]
                {{ repo.full_name }}
                ({{ commit.branch }} - {{ commit.sha[0:8] }})"
            body: |
                {{ commit.sha }}<br>
                {{ pipeline.status }}<br>
                {{ commit.author_email }}<br>
